apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-deployment
  labels:
    app: busy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy
  template:
    metadata:
      labels:
        app: busy
    spec:
      containers:
      - name: busy
        image: "k8s.gcr.io/busybox"
        command: [ "sleep", "1000000" ]
