kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-slave-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsan-default-storage-policy
  resources:
    requests:
      storage: 2Gi
